### ISSUE TITLE
Retrieving status of non-existing task returns internal server error "cannot cast id: Attribute error"

### ISSUE THREAD

**Issue by Jascha-N** [Donders-Institute/filer-gateway#2]
It would be nice if this would return a 404 not found instead.

**Comment by hurngchunlee** [comment]
@Jascha-N I looked into this issue, but the main issue is that the underlying task scheduling library I use ([bokchoy](https://github.com/thoas/bokchoy)) has a bug.  See this issue I created to the project: https://github.com/thoas/bokchoy/issues/31

For the time being, I have to fork this project and make my own fix (given that the author of this project doesn't seem to be very active on this project).  Anyway, it is at least fixed by now.  If the task doesn't exist, it returns 404.  See [this API document](http://dccn-pl001.dccn.nl:8080/v1/docs#/default/get_tasks__type___id_) for more information.
